apiVersion: v1
kind: Service
metadata:
  name: stellar-core
spec:
  clusterIP: None
  selector:
    app: stellar-core
  ports:
    - port: 11626
      targetPort: 11626
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stellar-core
  labels:
    app: stellar-core
spec:
  serviceName: "stellar-core"
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: stellar-core
  template:
    metadata:
      labels:
        app: stellar-core
    spec:
      containers:
      - name: stellar-core
        image: {{ .Values.worker.stellar_core_image }}
        imagePullPolicy: Always
        {{- if (.Values.worker).resources }}
        resources:
        {{ toYaml .Values.worker.resources | indent 6 }}
        {{- end }}
        command: ["/bin/sh", "/scripts/worker.sh"]
        ports:
        - containerPort: 11626
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        envFrom:
        - configMapRef:
            name: worker-config
        volumeMounts:
        - name: config
          mountPath: /config
        - name: script
          mountPath: /scripts
      volumes:
      - name: config
        configMap:
          name: stellar-core-config
      - name: script
        configMap:
          name: worker-script
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-script
data:
  worker.sh: |-
    {{- (.Files.Get "files/worker.sh") | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stellar-core-config
data:
  stellar-core.cfg: |-
    {{- (.Files.Get "files/stellar-core.cfg") | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-config
data:
  REDIS_HOST: "{{ .Values.redis.hostname}}"
  REDIS_PORT: "{{ .Values.redis.port}}"
  JOB_QUEUE: "{{ .Values.redis.job_queue }}"
  SUCCESS_QUEUE: "{{ .Values.redis.success_queue }}"
  FAILED_QUEUE: "{{ .Values.redis.failed_queue }}"
  PROGRESS_QUEUE: "{{ .Values.redis.progress_queue }}"
  METRICS: "{{ .Values.redis.metrics }}"
  RELEASE_NAME: "{{ .Release.Name }}"