redis:
  job_queue: "ranges"
  success_queue: "succeeded"
  failed_queue: "failed"
  progress_queue: "in_progress"
  resources:
    requests: 
      cpu: "100m"
      memory: "100Mi"

worker:
  stellar_core_image: "stellar/stellar-core:latest"
  replicas: 5
  resources:
    requests: 
      cpu: "1"
      memory: "10Gi"
      ephemeral_storage: "35Gi"
    limits:
      cpu: "4"
      memory: "30Gi"
      ephemeral_storage: "40Gi"

monitor:
  logging_interval_seconds: 10
  resources:
    requests: 
      cpu: "100m"
      memory: "100Mi"

range_generator:
  strategy: "uniform" # "uniform" or "logarithmic"
  params:
    starting_ledger: 0
    latest_ledger_num: 100000
    overlap_ledgers: 320
    uniform_ledgers_per_job: 16000 # only for strategy="uniform"
    logarithmic_floor_ledgers: 16000 # only for strategy="logarithmic"
